### ISSUE TITLE
help wanted : Naming Conventions

### ISSUE THREAD

**Issue by selvi-22** [Aravinth55/CarRentalManagementProject#1]
As per standards, follow the best practices for variables

![image](https://user-images.githubusercontent.com/106646977/182292985-591f0b01-fe1a-41af-9e99-ce731c08a60e.png)

![image](https://user-images.githubusercontent.com/106646977/182293234-5bacc289-30b9-4e06-9765-ad18a027b2dd.png)

![image](https://user-images.githubusercontent.com/106646977/182293334-6f0c7235-aead-4612-93e3-ad9c8f032ff0.png)

**Comment by Aravinth55** [comment]
naming conventions changed
